# Important documents

In [4]:
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import pandas as pd
from pathlib import Path
import re

In [5]:
def get_pdfs_from_page(url, download=False, output_dir="pdfs"):
    """
    Extract all PDF links from a webpage.

    Parameters
    ----------
    url : str
        URL of the webpage.
    download : bool, default=False
        Whether to download the PDFs.
    output_dir : str, default="pdfs"
        Directory where PDFs will be saved.

    Returns
    -------
    pd.DataFrame
        DataFrame with columns: name, url
    """

    headers = {"User-Agent": "Mozilla/5.0"}

    response = requests.get(url, headers=headers)
    response.raise_for_status()

    soup = BeautifulSoup(response.text, "html.parser")

    pdfs = []

    for a in soup.find_all("a", href=True):
        full_url = urljoin(url, a["href"])

        if ".pdf" in full_url.lower():
            name = a.get_text(strip=True)

            # Fallback to filename if anchor text is empty
            if not name:
                name = full_url.split("/")[-1]

            pdfs.append({
                "name": name,
                "url": full_url
            })

    df = pd.DataFrame(pdfs).drop_duplicates()

    if download and not df.empty:
        out_dir = Path(output_dir)
        out_dir.mkdir(parents=True, exist_ok=True)

        for _, row in df.iterrows():
            # Remove invalid filename characters
            safe_name = re.sub(r'[<>:"/\\|?*]', "_", row["name"])
            filename = out_dir / f"{safe_name}.pdf"

            r = requests.get(row["url"], headers=headers)
            r.raise_for_status()

            with open(filename, "wb") as f:
                f.write(r.content)

            print(f"Downloaded: {filename}")

    return df

## reg pracy

In [6]:
get_pdfs_from_page("https://www.bip.pw.edu.pl/Wewnetrzne-akty-prawne/Regulaminy/Regulamin-pracy-Politechniki-Warszawskiej", True, "../../data/raw/wazne_pdfy_zmiany/regulamin_pracy/")

Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_pracy\Regulamin pracy.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_pracy\Zarządzenie nr 9_2020 Rektora Politechniki Warszawskiej.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_pracy\Zarządzenie nr 49_2020 Rektora Politechniki Warszawskiej.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_pracy\Zarządzenie nr 83_2020 Rektora Politechniki Warszawskiej.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_pracy\Zarządzenie nr 125_2020 Rektora Politechniki Warszawskiej.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_pracy\Zarządzenie nr 166_2020 Rektora Politechniki Warszawskiej.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_pracy\Zarządzenie nr 168_2020 Rektora Politechniki Warszawskiej.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_pracy\Zarządzenie nr 10_2021 Rektora Politechniki Warszawskiej.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_pracy\Zarządzenie nr 113_2021 Rektora Politechniki Warszawskiej.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_pracy\Zarządzenie nr 62_2022 Rektora Politechniki Warszawskiej.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_pracy\Zarządzenie nr 32_2023 Rektora Politechniki Warszawskiej.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_pracy\Zarządzenie nr 46_2023 Rektora Politechniki Warszawskiej.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_pracy\Zarządzenie nr 59_2023 Rektora Politechniki Warszawskiej.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_pracy\Zarządzenie nr 31_2024 Rektora Politechniki Warszawskiej.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_pracy\Zarządzenie nr 47_2024 Rektora Politechniki Warszawskiej.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_pracy\Zarządzenie nr 92_2024 Rektora Politechniki Warszawskiej.pdf

,name,url
0,Regulamin pracy,https://www.bip.pw.edu.pl/var/pw/storage/origi...
1,Zarządzenie nr 9/2020 Rektora Politechniki War...,https://bip.pw.edu.pl/var/pw/storage/original/...
2,Zarządzenie nr 49/2020 Rektora Politechniki Wa...,https://bip.pw.edu.pl/var/pw/storage/original/...
3,Zarządzenie nr 83/2020 Rektora Politechniki Wa...,https://bip.pw.edu.pl/var/pw/storage/original/...
4,Zarządzenie nr 125/2020 Rektora Politechniki W...,https://bip.pw.edu.pl/var/pw/storage/original/...
5,Zarządzenie nr 166/2020 Rektora Politechniki W...,https://bip.pw.edu.pl/var/pw/storage/original/...
6,Zarządzenie nr 168/2020 Rektora Politechniki W...,https://bip.pw.edu.pl/var/pw/storage/original/...
7,Zarządzenie nr 10/2021 Rektora Politechniki Wa...,https://bip.pw.edu.pl/var/pw/storage/original/...
8,Zarządzenie nr 113/2021 Rektora Politechniki W...,https://bip.pw.edu.pl/var/pw/storage/original/...
9,Zarządzenie nr 62/2022 Rektora Politechniki Wa...,https://bip.pw.edu.pl/var/pw/storage/original/...
10,Zarządzenie nr 32/2023 Rektora Politechniki Wa...,https://bip.pw.edu.pl/var/pw/storage/original/...
11,Zarządzenie nr 46/2023 Rektora Politechniki Wa...,https://bip.pw.edu.pl/var/pw/storage/original/...
12,Zarządzenie nr 59/2023 Rektora Politechniki Wa...,https://www.bip.pw.edu.pl/var/pw/storage/origi...
13,Zarządzenie nr 31/2024 Rektora Politechniki Wa...,https://www.bip.pw.edu.pl/var/pw/storage/origi...
14,Zarządzenie nr 47/2024 Rektora Politechniki Wa...,https://www.bip.pw.edu.pl/var/pw/storage/origi...
15,Zarządzenie nr 92/2024 Rektora Politechniki Wa...,https://bip.pw.edu.pl/var/pw/storage/original/...

## reg studiow

In [7]:
get_pdfs_from_page("https://www.bip.pw.edu.pl/Wewnetrzne-akty-prawne/Regulaminy/Regulamin-studiow-w-Politechnice-Warszawskiej", True, "../../data/raw/wazne_pdfy_zmiany/regulamin_studiow/")

Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_studiow\Regulamin studiów w Politechnice Warszawskiej.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_studiow\Uchwała nr 363_XLIX_2019 Senatu Politechniki Warszawskiej.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_studiow\Uchwała nr 388_XLIX_2019 Senatu Politechniki Warszawskiej.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_studiow\Pismo okólne nr 1_2019 Rektora Politechniki Warszawskiej.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_studiow\Uchwała nr 57_L_2020 Senatu Politechniki Warszawskiej.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_studiow\Uchwała nr 167_L_2021 Senatu Politechniki Warszawskiej.pdf

,name,url
0,Regulamin studiów w Politechnice Warszawskiej,https://www.bip.pw.edu.pl/var/pw/storage/origi...
1,Uchwała nr 363/XLIX/2019 Senatu Politechniki W...,https://bip.pw.edu.pl/var/pw/storage/original/...
2,Uchwała nr 388/XLIX/2019 Senatu Politechniki W...,https://bip.pw.edu.pl/var/pw/storage/original/...
3,Pismo okólne nr 1/2019 Rektora Politechniki Wa...,https://bip.pw.edu.pl/var/pw/storage/original/...
4,Uchwała nr 57/L/2020 Senatu Politechniki Warsz...,https://bip.pw.edu.pl/var/pw/storage/original/...
5,Uchwała nr 167/L/2021 Senatu Politechniki Wars...,https://bip.pw.edu.pl/var/pw/storage/original/...

## reg swiadczen

In [8]:
get_pdfs_from_page("https://www.bip.pw.edu.pl/Wewnetrzne-akty-prawne/Dokumenty-Rektora-PW/Zarzadzenia-Rektora/2021/Zarzadzenie-nr-78-2021-Rektora-Politechniki-Warszawskiej-z-dnia-13-wrzesnia-2021-r", True, "../../data/raw/wazne_pdfy_zmiany/regulamin_swiadczen/")

Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_swiadczen\w sprawie wprowadzenia Regulaminu świadczeń dla studentów Politechniki Warszawskiej na rok akademicki 2021_2022.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_swiadczen\Pobierz plik.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_swiadczen\Regulamin świadczeń dla studentów Politechniki Warszawskiej na rok akademicki 2021_2022.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_swiadczen\Pobierz plik.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_swiadczen\Załącznik nr 1 do Regulaminu świadczeń dla studentów Politechniki Warszawskiej na rok akademicki 2021_2022.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_swiadczen\Pobierz plik.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_swiadczen\Załącznik nr 2 do Regulaminu świadczeń dla studentów Politechniki Warszawskiej na rok akademicki 2021_2022.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_swiadczen\Pobierz plik.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_swiadczen\Załącznik nr 3 do Regulaminu świadczeń dla studentów Politechniki Warszawskiej na rok akademicki 2021_2022.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_swiadczen\Pobierz plik.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_swiadczen\Załącznik nr 4 do Regulaminu świadczeń dla studentów Politechniki Warszawskiej na rok akademicki 2021_2022.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_swiadczen\Pobierz plik.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_swiadczen\Załącznik nr 5 do Regulaminu świadczeń dla studentów Politechniki Warszawskiej na rok akademicki 2021_2022.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_swiadczen\Pobierz plik.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_swiadczen\Załącznik nr 6 do Regulaminu świadczeń dla studentów Politechniki Warszawskiej na rok akademicki 2021_2022.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_swiadczen\Pobierz plik.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_swiadczen\Załącznik nr 7 do Regulaminu świadczeń dla studentów Politechniki Warszawskiej na rok akademicki 2021_2022.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_swiadczen\Pobierz plik.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_swiadczen\Załącznik nr 8 do Regulaminu świadczeń dla studentów Politechniki Warszawskiej na rok akademicki 2021_2022.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_swiadczen\Pobierz plik.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_swiadczen\Załącznik nr 9 do Regulaminu świadczeń dla studentów Politechniki Warszawskiej na rok akademicki 2021_2022.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_swiadczen\Pobierz plik.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_swiadczen\Załącznik nr 10 do Regulaminu świadczeń dla studentów Politechniki Warszawskiej na rok akademicki 2021_2022.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_swiadczen\Pobierz plik.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_swiadczen\Załącznik nr 11 do Regulaminu świadczeń dla studentów Politechniki Warszawskiej na rok akademicki 2021_2022.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_swiadczen\Pobierz plik.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_swiadczen\zmieniające zarządzenie nr 78_2021 Rektora Politechniki Warszawskiej w sprawie wprowadzenia Regulaminu świadczeń dla studentów Politechniki Warszawskiej na rok akademicki 2021_2022.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_swiadczen\Pobierz plik.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_swiadczen\zmieniające zarządzenie nr 78_2021 Rektora PW w sprawie wprowadzenia Regulaminu świadczeń dla studentów Politechniki Warszawskiej na rok akademicki 2021_2022.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\regulamin_swiadczen\Pobierz plik.pdf

,name,url
0,w sprawie wprowadzenia Regulaminu świadczeń dl...,https://www.bip.pw.edu.pl/var/pw/storage/origi...
1,Pobierz plik,https://www.bip.pw.edu.pl/content/download/502...
2,Regulamin świadczeń dla studentów Politechniki...,https://www.bip.pw.edu.pl/var/pw/storage/origi...
3,Pobierz plik,https://www.bip.pw.edu.pl/content/download/502...
4,Załącznik nr 1 do Regulaminu świadczeń dla stu...,https://www.bip.pw.edu.pl/var/pw/storage/origi...
5,Pobierz plik,https://www.bip.pw.edu.pl/content/download/502...
6,Załącznik nr 2 do Regulaminu świadczeń dla stu...,https://www.bip.pw.edu.pl/var/pw/storage/origi...
7,Pobierz plik,https://www.bip.pw.edu.pl/content/download/502...
8,Załącznik nr 3 do Regulaminu świadczeń dla stu...,https://www.bip.pw.edu.pl/var/pw/storage/origi...
9,Pobierz plik,https://www.bip.pw.edu.pl/content/download/502...
10,Załącznik nr 4 do Regulaminu świadczeń dla stu...,https://www.bip.pw.edu.pl/var/pw/storage/origi...
11,Pobierz plik,https://www.bip.pw.edu.pl/content/download/502...
12,Załącznik nr 5 do Regulaminu świadczeń dla stu...,https://www.bip.pw.edu.pl/var/pw/storage/origi...
13,Pobierz plik,https://www.bip.pw.edu.pl/content/download/502...
14,Załącznik nr 6 do Regulaminu świadczeń dla stu...,https://www.bip.pw.edu.pl/var/pw/storage/origi...
15,Pobierz plik,https://www.bip.pw.edu.pl/content/download/502...
16,Załącznik nr 7 do Regulaminu świadczeń dla stu...,https://www.bip.pw.edu.pl/var/pw/storage/origi...
17,Pobierz plik,https://www.bip.pw.edu.pl/content/download/502...
18,Załącznik nr 8 do Regulaminu świadczeń dla stu...,https://www.bip.pw.edu.pl/var/pw/storage/origi...
19,Pobierz plik,https://www.bip.pw.edu.pl/content/download/502...
20,Załącznik nr 9 do Regulaminu świadczeń dla stu...,https://www.bip.pw.edu.pl/var/pw/storage/origi...
21,Pobierz plik,https://www.bip.pw.edu.pl/content/download/502...
22,Załącznik nr 10 do Regulaminu świadczeń dla st...,https://www.bip.pw.edu.pl/var/pw/storage/origi...
23,Pobierz plik,https://www.bip.pw.edu.pl/content/download/502...
24,Załącznik nr 11 do Regulaminu świadczeń dla st...,https://www.bip.pw.edu.pl/var/pw/storage/origi...
25,Pobierz plik,https://www.bip.pw.edu.pl/content/download/502...
26,zmieniające zarządzenie nr 78/2021 Rektora Pol...,https://www.bip.pw.edu.pl/var/pw/storage/origi...
27,Pobierz plik,https://www.bip.pw.edu.pl/content/download/531...
28,zmieniające zarządzenie nr 78/2021 Rektora PW ...,https://www.bip.pw.edu.pl/var/pw/storage/origi...
29,Pobierz plik,https://www.bip.pw.edu.pl/content/download/534...

In [10]:
get_pdfs_from_page("https://www.bip.pw.edu.pl/Wewnetrzne-akty-prawne/Dokumenty-Senatu-PW/Uchwaly-Senatu-PW/2025-LI/Uchwala-nr-170-LI-2025-Senatu-Politechniki-Warszawskiej-z-dnia-25-czerwca-2025-r", True, "../../data/raw/wazne_pdfy_zmiany/uchwala_rekrutacyjna/")

Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\uchwala_rekrutacyjna\w sprawie warunków, trybu i terminu rekrutacji na jednolite studia magisterskie oraz studia pierwszego i drugiego stopnia, profili kształcenia oraz form tych studiów na poszczególnych kierunkach, prowadzonych w roku akademickim 2026_2027.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\uchwala_rekrutacyjna\Pobierz plik.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\uchwala_rekrutacyjna\Załącznik nr 1 do uchwały nr 170_LI_2025 Senatu PW z dnia 25 czerwca 2025 r..pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\uchwala_rekrutacyjna\Pobierz plik.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\uchwala_rekrutacyjna\Załącznik nr 2 do uchwały nr 170_LI_2025 Senatu PW z dnia 25 czerwca 2025 r..pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\uchwala_rekrutacyjna\Pobierz plik.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\uchwala_rekrutacyjna\Załącznik nr 3 do uchwały nr 170_LI_2025 Senatu PW z dnia 25 czerwca 2025 r..pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\uchwala_rekrutacyjna\Pobierz plik.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\uchwala_rekrutacyjna\Załącznik nr 4 do uchwały nr 170_LI_2025 Senatu PW z dnia 25 czerwca 2025 r..pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\uchwala_rekrutacyjna\Pobierz plik.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\uchwala_rekrutacyjna\Załącznik nr 5 do uchwały nr 170_LI_2025 Senatu PW z dnia 25 czerwca 2025 r..pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\uchwala_rekrutacyjna\Pobierz plik.pdf

OSError: [Errno 22] Invalid argument: '..\\..\\data\\raw\\wazne_pdfy_zmiany\\uchwala_rekrutacyjna\\Uchwała nr 257_LI_2026 Senatu Politechniki Warszawskiej z dnia 22 kwietnia 2026 r. zmieniająca uchwałę nr 170_LI_2025 Senatu Politechniki Warszawskiej w sprawie warunków trybu i terminu rekrutacji na jednolite studia magisterskie oraz studia pierwszego i drugiego stopnia, profili kształcenia oraz form tych studiów na poszczególnych kierunkach, prowadzonych w roku akademickim 2026_2027.pdf'

## Uchwala ukladania programu

In [13]:
get_pdfs_from_page("https://www.bip.pw.edu.pl/Wewnetrzne-akty-prawne/Dokumenty-Senatu-PW/Uchwaly-Senatu-PW/2020-L/Uchwala-nr-58-L-2020-z-dnia-25-11-2020", True, "../../data/raw/wazne_pdfy_zmiany/uchwala_ustalania_programu/")

Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\uchwala_ustalania_programu\w sprawie ustalania programów studiów w Politechnice Warszawskiej.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\uchwala_ustalania_programu\Pobierz plik.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\uchwala_ustalania_programu\Załącznik do uchwały nr 58_L_2020 Senatu PW z dnia 25_11_2020.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\uchwala_ustalania_programu\Pobierz plik.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\uchwala_ustalania_programu\Uchwała nr 33_LI_2024 Senatu Politechniki Warszawskiej z dnia 27 listopada 2024 r. zmieniająca uchwałę nr 58_L_2020 Senatu PW w sprawie ustalania programów studiów w Politechnice Warszawskiej.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\uchwala_ustalania_programu\Pobierz plik.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\uchwala_ustalania_programu\Załącznik do uchwały 33_LI_2024 Senatu PW z dnia 27 listopada 2024 r..pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\uchwala_ustalania_programu\Pobierz plik.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\uchwala_ustalania_programu\Uchwała nr 168_LI_2025 Senatu Politechniki Warszawskiej z dnia 25 czerwca 2025 r. zmieniająca uchwałę nr 58_L_2020 Senatu PW w sprawie ustalania programów studiów w Politechnice Warszawskiej.pdf
Downloaded: ..\..\data\raw\wazne_pdfy_zmiany\uchwala_ustalania_programu\Pobierz plik.pdf

,name,url
0,w sprawie ustalania programów studiów w Polite...,https://www.bip.pw.edu.pl/var/pw/storage/origi...
1,Pobierz plik,https://www.bip.pw.edu.pl/content/download/446...
2,Załącznik do uchwały nr 58/L/2020 Senatu PW z ...,https://www.bip.pw.edu.pl/var/pw/storage/origi...
3,Pobierz plik,https://www.bip.pw.edu.pl/content/download/446...
4,Uchwała nr 33/LI/2024 Senatu Politechniki Wars...,https://www.bip.pw.edu.pl/var/pw/storage/origi...
5,Pobierz plik,https://www.bip.pw.edu.pl/content/download/712...
6,Załącznik do uchwały 33/LI/2024 Senatu PW z dn...,https://www.bip.pw.edu.pl/var/pw/storage/origi...
7,Pobierz plik,https://www.bip.pw.edu.pl/content/download/712...
8,Uchwała nr 168/LI/2025 Senatu Politechniki War...,https://www.bip.pw.edu.pl/var/pw/storage/origi...
9,Pobierz plik,https://www.bip.pw.edu.pl/content/download/753...